/**
 * 
 */
package com.panasonic.b2bacns.bizportal.rc;

/**
 * @author simanchal.patra
 * 
 */
public enum RCOperation {
	POWERSTATUS, MODE, TEMPERATURE, FANSPEED, WINDDIRECTION, ENERGY_SAVING, 
	PROHIBITION_POWERSTATUS, PROHIBITON_MODE, PROHIBITION_FANSPEED, PROHIBITION_WINDRIECTION, 
	PROHIBITION_SET_TEMP, PROHIBITION_ENERGY_SAVING;
}
